server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vagetable?characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true